---
- name: Ensure basic packages are installed
  apt:
    name:
      - python3
      - python3-pip
      - net-tools
      - iproute2
      - procps
      - psmisc
      - tree
      - curl
      - vim
      - nano
    state: present
    update_cache: yes

- name: Configure static host aliases
  blockinfile:
    path: /etc/hosts
    marker: "# {mark} MORRIS WORM LAB HOSTS"
    block: |
      10.10.10.5 attacker
      10.30.30.5 analyst
      10.20.20.11 victim1
      10.20.20.12 victim2
      10.20.20.13 victim3

- name: Enable SSH password authentication for lab users
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
  notify: Reload SSH service
