---
roles:
  - src: https://github.com/cyberrangecz/ansible-role-user-access.git
    name: user-access
  - src: https://github.com/cyberrangecz/ansible-role-hosts-aliases.git
    name: hosts-aliases
  - src: https://github.com/cyberrangecz/ansible-role-sandbox-logging.git
    name: sandbox-logging
